### ISSUE TITLE
Example not working (points not showing on map, neither on Mapbox, nor on Google Maps with Deck.gl)

### ISSUE THREAD

**Issue by florinvirdol** [chargetrip/clusterbuster#58]
Hi, guys, 
Seems you've done a great work with the filtering, clustering and caching.
I'm really excited about this project and i'm eager to try it!  

I'm working on a project on plotting Deck.gl layers (MVTLayer) on top of Google Maps from a vector tile server. 

For the vector tile server, i already tried multiple approaches: 
- nodejs server serving from mbtiles
- TileServer serving from mbtiles
- Martin serving from PostGIS
- TODO: ClusterBuster serving from PostGIS clustered points (and filtered) 

I want to try to integrate and to serve from ClusterBuster server some clustered points saved in PostGIS.

I tried building and running the example provided but somehow, i'm not able to do this. 
Tried with the provided mapbox example from `clusterbuster/example/mapbox.html` (with my mapbox token) and with my Deck.gl example, but nothing appears on the maps.  

Any help or advice is really appreciate!
Thank you in advance!

As stated in the clusterbuster/example/readme.md i created an `.env` file with PostGIS connections settings.

After running the following commands: 
```
yarn
yarn start
```

i get this output:
```
C:\zFVStuff\Dentsu\Google Maps - Deck.gl\_Servers\ClusterBuster\clusterbuster-master> yarn start
yarn run v1.22.4
$ yarn build && ts-node example/express.ts
$ rollup --config rollup.config.js

./lib/index.ts → dist/index.d.ts...
created dist/index.d.ts in 5.7s

./lib/index.ts → dist/index.js...
created dist/index.js in 5.1s
attempting to create supporting SQL functions
failure in creating First SQL function
failure in creating TileBBox SQL function
failure in creating TileDoubleBBox SQL function
Example app listening on port 3005!

send3663284b-0e58-4587-af82-b35604a99303: 4.964ms
3663284b-0e58-4587-af82-b35604a99303: 817.819ms
sendd0bdd671-1f47-4b40-84ba-2fed6adfd045: 3.451ms
d0bdd671-1f47-4b40-84ba-2fed6adfd045: 1276.588ms
sendcd36f672-4c4b-4a95-b772-7584e6eb8c55: 1.349ms
cd36f672-4c4b-4a95-b772-7584e6eb8c55: 1754.146ms
```

First question would be whether those failures in creating First, TileBBox, TileDoubleBBox SQL functions might be the actual problem?!
I saw those errors comes from the clusterbuster/lib/supporting.ts . Could these errors happen because of wrong PostGIS connection?

If not, the requests seems to be ok, returning status 200 but nothing appears on the map (neither your Mapbox, or my Google Maps).
Also, it's curious that all tile responses seems to have the same size 216 B.

![image](https://user-images.githubusercontent.com/2658166/93871233-fca39000-fcd6-11ea-8579-38bd8565cf84.png)

The data was imported ok in the PostGIS database. 
![image](https://user-images.githubusercontent.com/2658166/93875143-1f38a780-fcdd-11ea-90a0-9e8688f58c69.png)

**Comment by cosmin-petrescu** [comment]
Hello,

The errors are generated by the fact those PostgreSQL functions already exists, they were created in a previous run. Did you tried to see the response which is coming from ClusterBurster, and try to decode the MVT (please make sure you unzip it first)?

**Comment by florinvirdol** [comment]
Hi, @cosmin-petrescu 
Thank you for your fast reply. 

I ran the provided express server `clusterbuster/example/express.ts` and for frontend, tried with the provided mapbox example from `clusterbuster/example/mapbox.html` but nothing appears on mapbox map (nor on Google maps with my Deck.gl example).


How do you suggest to see the response coming from ClusterBuster? 

In the Chrome network tab, in none of the sub-tabs Preview or Response i can't see any data.
![image](https://user-images.githubusercontent.com/2658166/93887498-7182c400-fcef-11ea-8d3c-ee9be5f14079.png)

![image](https://user-images.githubusercontent.com/2658166/93887745-c45c7b80-fcef-11ea-9a36-939436888b40.png)

I also tried logging the result tile in the express server in the success function, 
```
server({ 
   ...//excluded for visibility 
}).then(result => {
   ...//excluded for visibility 

   console.log(result)

   res.status(200).send(result);
})
```
and below is the output, i get `undefined`:
![image](https://user-images.githubusercontent.com/2658166/93888527-ca9f2780-fcf0-11ea-92f7-6d544294529e.png)

**Comment by florinvirdol** [comment]
@cosmin-petrescu any thoughts on my last comment regarding `undefined` response coming from ClusterBurster?
Thank you!

**Comment by cosmin-petrescu** [comment]
Hello,

Can you try edit `example/express.ts` after line `attributes: ['status', 'speed'],` add `debug: true,` and run again `ts-node .\example\express.ts`. This will enable the debug mode which is more verbose. You can try to copy the query from the log and run it in pgAdmin 4.

I just tried the example with a clean clone and it worked for me.
<img width="570" alt="Screenshot 2020-09-23 at 15 41 34" src="https://user-images.githubusercontent.com/2471291/94014664-85dcc480-fdb4-11ea-9050-8e10645b731b.png">

**Comment by florinvirdol** [comment]
This is the log generated after added `debug: true`. 
At the end there seems to be an error `Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:205:27)`

```
WITH base_query AS (
SELECT
  wkb_geometry AS center,
  1 AS size,
  0 AS clusterNo,
  13 AS expansionZoom, status, speed
FROM public.points
WHERE
        ST_Intersects(TileBBox(7, 66, 43, 3857), ST_Transform(wkb_geometry, 3857))

),
clustered_12 AS (
SELECT
  center,
  expansionZoom,
  clusterNo AS previousClusterNo,
  size,
  ST_ClusterDBSCAN(center, 0.003662109375, 1) over () as clusters, status, speed
FROM base_query
),
grouped_clusters_12 AS (
SELECT
  SUM(size) as size,
  clusters AS clusterNo,
  (
    CASE COUNT(previousClusterNo)
      WHEN 1 THEN FIRST(expansionZoom)
      ELSE 13 END
  ) AS expansionZoom, FIRST(status) as status, FIRST(speed) as speed,
  ST_Centroid(ST_Collect(center)) as center
FROM clustered_12
GROUP BY clusters
),
clustered_11 AS (
SELECT
  center,
  expansionZoom,
  clusterNo AS previousClusterNo,
  size,
  ST_ClusterDBSCAN(center, 0.00732421875, 1) over () as clusters, status, speed
FROM grouped_clusters_12
),
grouped_clusters_11 AS (
SELECT
  SUM(size) as size,
  clusters AS clusterNo,
  (
    CASE COUNT(previousClusterNo)
      WHEN 1 THEN FIRST(expansionZoom)
      ELSE 12 END
  ) AS expansionZoom, FIRST(status) as status, FIRST(speed) as speed,
  ST_Centroid(ST_Collect(center)) as center
FROM clustered_11
GROUP BY clusters
),
clustered_10 AS (
SELECT
  center,
  expansionZoom,
  clusterNo AS previousClusterNo,
  size,
  ST_ClusterDBSCAN(center, 0.0146484375, 1) over () as clusters, status, speed
FROM grouped_clusters_11
),
grouped_clusters_10 AS (
SELECT
  SUM(size) as size,
  clusters AS clusterNo,
  (
    CASE COUNT(previousClusterNo)
      WHEN 1 THEN FIRST(expansionZoom)
      ELSE 11 END
  ) AS expansionZoom, FIRST(status) as status, FIRST(speed) as speed,
  ST_Centroid(ST_Collect(center)) as center
FROM clustered_10
GROUP BY clusters
),
clustered_9 AS (
SELECT
  center,
  expansionZoom,
  clusterNo AS previousClusterNo,
  size,
  ST_ClusterDBSCAN(center, 0.029296875, 1) over () as clusters, status, speed
FROM grouped_clusters_10
),
grouped_clusters_9 AS (
SELECT
  SUM(size) as size,
  clusters AS clusterNo,
  (
    CASE COUNT(previousClusterNo)
      WHEN 1 THEN FIRST(expansionZoom)
      ELSE 10 END
  ) AS expansionZoom, FIRST(status) as status, FIRST(speed) as speed,
  ST_Centroid(ST_Collect(center)) as center
FROM clustered_9
GROUP BY clusters
),
clustered_8 AS (
SELECT
  center,
  expansionZoom,
  clusterNo AS previousClusterNo,
  size,
  ST_ClusterDBSCAN(center, 0.05859375, 1) over () as clusters, status, speed
FROM grouped_clusters_9
),
grouped_clusters_8 AS (
SELECT
  SUM(size) as size,
  clusters AS clusterNo,
  (
    CASE COUNT(previousClusterNo)
      WHEN 1 THEN FIRST(expansionZoom)
      ELSE 9 END
  ) AS expansionZoom, FIRST(status) as status, FIRST(speed) as speed,
  ST_Centroid(ST_Collect(center)) as center
FROM clustered_8
GROUP BY clusters
),
clustered_7 AS (
SELECT
  center,
  expansionZoom,
  clusterNo AS previousClusterNo,
  size,
  ST_ClusterDBSCAN(center, 0.1171875, 1) over () as clusters, status, speed
FROM grouped_clusters_8
),
grouped_clusters_7 AS (
SELECT
  SUM(size) as size,
  clusters AS clusterNo,
  (
    CASE COUNT(previousClusterNo)
      WHEN 1 THEN FIRST(expansionZoom)
      ELSE 8 END
  ) AS expansionZoom, FIRST(status) as status, FIRST(speed) as speed,
  ST_Centroid(ST_Collect(center)) as center
FROM clustered_7
GROUP BY clusters
),
tile AS (
SELECT
  ST_AsMVTGeom(ST_Transform(center, 3857), TileBBox(7, 66, 43, 3857), 4096, 256, false) AS geom,
  jsonb_build_object(
    'count', size,
    'expansionZoom', expansionZoom,
    'lng', ST_X(ST_Transform(center, 4326)),
    'lat', ST_Y(ST_Transform(center, 4326)), 'status', status, 'speed', speed
  ) AS attributes
FROM grouped_clusters_7
)
SELECT ST_AsMVT(tile, 'points', 4096, 'geom') AS mvt FROM tile
{
  e: Error: read ECONNRESET
      at TCP.onStreamRead (internal/stream_base_commons.js:205:27) {
    errno: 'ECONNRESET',
    code: 'ECONNRESET',
    syscall: 'read'
  }
}
```

**Comment by cosmin-petrescu** [comment]
The env config file should be `.env` without dev.

**Comment by florinvirdol** [comment]
.env was initially and then renamed. 

Tried with both, but the same error as above, it seems it tries to connect with my username: 

```SELECT ST_AsMVT(tile, 'points', 4096, 'geom') AS mvt FROM tile
{
  e: error: password authentication failed for user "fvirdol" 
.....
```

**Comment by cosmin-petrescu** [comment]
Now I got it. `yarn build` you should run in the root of clusterbuster. The `.env` file should be placed in the `example` folder and the from that folder run `ts-node express.ts`.

```
yarn build
cd example
nano .env
ts-node express.ts
```

**Comment by florinvirdol** [comment]
It finally worked!! Thank you very much, @cosmin-petrescu ! 

Lately, i ran from the root of clusterbuster with `ts-node .\example\express.ts` or with `yarn start` (that underneath uses the same and it tries to connect with my user instead of `.env` config file)

After running `ts-node express.ts` from the `example` folder it took into account the `.env` config file with `postgres` user instead of my user.

```
send: cf60bd6e-bedb-475d-8fd2-96b8064b40fd: 5.539ms
cf60bd6e-bedb-475d-8fd2-96b8064b40fd: 17.872ms
WITH base_query AS (
SELECT
  wkb_geometry AS center,
  1 AS size,
  0 AS clusterNo,
  13 AS expansionZoom, status, speed
FROM public.points
WHERE
        ST_Intersects(TileBBox(8, 135, 72, 3857), ST_Transform(wkb_geometry, 3857))

),
clustered_12 AS (
SELECT
  center,
  expansionZoom,
  clusterNo AS previousClusterNo,
  size,
  ST_ClusterDBSCAN(center, 0.003662109375, 1) over () as clusters, status, speed
FROM base_query
),
grouped_clusters_12 AS (
SELECT
  SUM(size) as size,
  clusters AS clusterNo,
  (
    CASE COUNT(previousClusterNo)
      WHEN 1 THEN FIRST(expansionZoom)
      ELSE 13 END
  ) AS expansionZoom, FIRST(status) as status, FIRST(speed) as speed,
  ST_Centroid(ST_Collect(center)) as center
FROM clustered_12
GROUP BY clusters
),
clustered_11 AS (
SELECT
  center,
  expansionZoom,
  clusterNo AS previousClusterNo,
  size,
  ST_ClusterDBSCAN(center, 0.00732421875, 1) over () as clusters, status, speed
FROM grouped_clusters_12
),
grouped_clusters_11 AS (
SELECT
  SUM(size) as size,
  clusters AS clusterNo,
  (
    CASE COUNT(previousClusterNo)
      WHEN 1 THEN FIRST(expansionZoom)
      ELSE 12 END
  ) AS expansionZoom, FIRST(status) as status, FIRST(speed) as speed,
  ST_Centroid(ST_Collect(center)) as center
FROM clustered_11
GROUP BY clusters
),
clustered_10 AS (
SELECT
  center,
  expansionZoom,
  clusterNo AS previousClusterNo,
  size,
  ST_ClusterDBSCAN(center, 0.0146484375, 1) over () as clusters, status, speed
FROM grouped_clusters_11
),
grouped_clusters_10 AS (
SELECT
  SUM(size) as size,
  clusters AS clusterNo,
  (
    CASE COUNT(previousClusterNo)
      WHEN 1 THEN FIRST(expansionZoom)
      ELSE 11 END
  ) AS expansionZoom, FIRST(status) as status, FIRST(speed) as speed,
  ST_Centroid(ST_Collect(center)) as center
FROM clustered_10
GROUP BY clusters
),
clustered_9 AS (
SELECT
  center,
  expansionZoom,
  clusterNo AS previousClusterNo,
  size,
  ST_ClusterDBSCAN(center, 0.029296875, 1) over () as clusters, status, speed
FROM grouped_clusters_10
),
grouped_clusters_9 AS (
SELECT
  SUM(size) as size,
  clusters AS clusterNo,
  (
    CASE COUNT(previousClusterNo)
      WHEN 1 THEN FIRST(expansionZoom)
      ELSE 10 END
  ) AS expansionZoom, FIRST(status) as status, FIRST(speed) as speed,
  ST_Centroid(ST_Collect(center)) as center
FROM clustered_9
GROUP BY clusters
),
clustered_8 AS (
SELECT
  center,
  expansionZoom,
  clusterNo AS previousClusterNo,
  size,
  ST_ClusterDBSCAN(center, 0.05859375, 1) over () as clusters, status, speed
FROM grouped_clusters_9
),
grouped_clusters_8 AS (
SELECT
  SUM(size) as size,
  clusters AS clusterNo,
  (
    CASE COUNT(previousClusterNo)
      WHEN 1 THEN FIRST(expansionZoom)
      ELSE 9 END
  ) AS expansionZoom, FIRST(status) as status, FIRST(speed) as speed,
  ST_Centroid(ST_Collect(center)) as center
FROM clustered_8
GROUP BY clusters
),
tile AS (
SELECT
  ST_AsMVTGeom(ST_Transform(center, 3857), TileBBox(8, 135, 72, 3857), 4096, 256, false) AS geom,
  jsonb_build_object(
    'count', size,
    'expansionZoom', expansionZoom,
    'lng', ST_X(ST_Transform(center, 4326)),
    'lat', ST_Y(ST_Transform(center, 4326)), 'status', status, 'speed', speed
  ) AS attributes
FROM grouped_clusters_8
)
SELECT ST_AsMVT(tile, 'points', 4096, 'geom') AS mvt FROM tile
<Buffer 1f 8b 08 00 00 00 00 00 00 0a 93 6a 63 e4 62 2b c8 cf cc 2b 29 16 12 17 e2 61 60 60 64 64 62 62 66 66 61 61 65 95 60 54 62 e5 dc 27 7a 43 45 8a 39 27 ... 104 more bytes>
send: 253599d2-1a9c-4c5c-9d18-51193e7fe610: 0.509ms
253599d2-1a9c-4c5c-9d18-51193e7fe610: 12.957ms
<Buffer 1f 8b 08 00 00 00 00 00 00 0a 93 da ca c8 c5 56 90 9f 99 57 52 2c 24 2e c4 c3 c0 c0 c8 c8 c4 c4 cc cc c2 c2 ca 2a c1 a8 c4 ca f9 43 fd 13 37 58 82 8d ... 134 more bytes>
```

**Comment by florinvirdol** [comment]
@cosmin-petrescu  Before closing this issue, please, i have two final question regarding disabling clustering and serving other geo data: 
- It's possible to serve all the points without being clustered? (filtering or without filtering)
- Similar to Martin or Tegola servers, it's possible to serve vector tiles with ClusterBuster from PostGIS in the form of shapes (eg.: polygons, multi-polygons - not only points) and without being clustered (filtering or without filtering)?

Where can i ask these types of questions if here (issues sections) isn't the best place to do it?
Thank you very much!

**Comment by cosmin-petrescu** [comment]
For the first question the answer is yes, you can configure the zoom level from where to create clusters, so if you set it to 0 (I think), clusterbuster will not do clustering anymore.
For the second question, I'm not sure, we never tried to that. The main idea behind clusterbuster was to do clustering and filtering over high amount of points, that's why shapes were out of the scope.

**Comment by florinvirdol** [comment]
Thank you! 
Yeah, it works disabling clustering with the zoom level.

I asked the second question, because i wanted to know whether i can serve only from ClusterBuster (points and shapes), without the need to have an additional server (Martin) only for shapes. :(

**Comment by cosmin-petrescu** [comment]
Hey, you can try to see if it works and if it does, maybe you can add a PR to update the docs :D

**Comment by florinvirdol** [comment]
Hi, again! 
I tried it and it seems it doesn't serve shapes to the fronted. 

I believe it will be better to open another issue - question type. 

Don't know if it's something that i need to configure for serving shapes, but in short words, i'm receiving the following error: 
```
SELECT ST_AsMVT(tile, 'points', 4096, 'geom') AS mvt FROM tile
{
  e: error: Argument to ST_X() must have type POINT
```

I did set the table to a shapes collection from PostGIS, changed the `maxZoomLevel = 0` and enabled the debugging `debug: true`, but i have the following logs:

```
WITH base_query AS (
SELECT
  geom AS center,
  1 AS size,
  0 AS clusterNo,
  1 AS expansionZoom
FROM postalarea
WHERE
        ST_Intersects(TileBBox(7, 64, 42, 3857), ST_Transform(geom, 3857))

),
tile AS (
SELECT
  ST_AsMVTGeom(ST_Transform(center, 3857), TileBBox(7, 64, 42, 3857), 4096, 256, false) AS geom,
  jsonb_build_object(
    'count', size,
    'expansionZoom', expansionZoom,
    'lng', ST_X(ST_Transform(center, 4326)),
    'lat', ST_Y(ST_Transform(center, 4326))
  ) AS attributes
FROM base_query
)
SELECT ST_AsMVT(tile, 'points', 4096, 'geom') AS mvt FROM tile
{
  e: error: Argument to ST_X() must have type POINT
      at Connection.parseE (C:\zFVStuff\D\Google Maps - Deck.gl\_Servers\ClusterBuster\clusterbuster-master\node_modules\pg\lib\connection.js:614:13)
      at Connection.parseMessage (C:\zFVStuff\D\Google Maps - Deck.gl\_Servers\ClusterBuster\clusterbuster-master\node_modules\pg\lib\connection.js:413:19)
      at Socket.<anonymous> (C:\zFVStuff\D\Google Maps - Deck.gl\_Servers\ClusterBuster\clusterbuster-master\node_modules\pg\lib\connection.js:129:22)
      at Socket.emit (events.js:311:20)
      at Socket.EventEmitter.emit (domain.js:482:12)
      at addChunk (_stream_readable.js:294:12)
      at readableAddChunk (_stream_readable.js:275:11)
      at Socket.Readable.push (_stream_readable.js:209:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
    name: 'error',
    length: 95,
    severity: 'ERROR',
    code: 'XX000',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'lwgeom_pg.c',
    line: '243',
    routine: 'pg_error'
  }
}
```

**Comment by cosmin-petrescu** [comment]
Ok, so because we are returning lat and lng of a point that means we cannot work with shapes which have multiple coordinates.
