### ISSUE TITLE
Maintenance status?

### ISSUE THREAD

**Issue by edtjones** [chargetrip/clusterbuster#77]
Hi folks,

I'm investigating MVT generation options and `clusterbuster` is interesting because it's the only thing which can dynamically cluster on the serverside which I've come across. But I see there are quite a few automated PRs waiting for merge; are you still using this in production? Don't want add a dependency on something you've moved on from :)

Thanks

Ed

**Comment by cosmin-petrescu** [comment]
Hello,

Because our needs changed since we developed this, we moved away to a private custom implementation of [supercluser](https://www.npmjs.com/package/supercluster) on server side. If you would like to maintain this package, I'm more than glad to give you access.

Best reagrds.

**Comment by edtjones** [comment]
thanks @cosmin-petrescu - I'll see if it fits with our needs and raise another issue if I would like commit access
